### ISSUE TITLE
provision on the page of the portal to display the list of beneficiaries one side and another side observation of the student/institution regarding correction of the Bank detail

### ISSUE THREAD

**Issue by m-madhukar** [m-madhukar/hpepass#12]
provision on the page of the portal to display the list of beneficiaries one side and another side observation of the student/institution regarding correction of the Bank detail

**Comment by radhikasahasra7** [comment]
Completed list of beneficiaries one side and another side observation of the student/institution regarding correction of the Bank detail.completed on 12/04/2018
