### ISSUE TITLE
Pre-Matric SC and OBC income ceiling from 2lakh to 2.5 lak for 2017-18

### ISSUE THREAD

**Issue by m-madhukar** [m-madhukar/hpepass#6]
pls refer client mail on  5th February 2018 for  Pre Matric OBC and 19 February 2018 for Pre Matric SC family income limit changes from 2 lakh to 2.5lakh and fee details.
Need to change code level.

**Comment by Vanigithub** [comment]
changed the income limit closed on 16/03/2018
